name: Build AKS Anywhere partitioned VM Image

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group to operate in'
        required: true
        type: string
      location:
        description: 'Location for all resources'
        required: false
        default: 'eastus2'
        type: string
      create_sig_version:
        description: 'Whether to create a new SIG image version (true/false)'
        required: false
        default: 'true'
        type: string

permissions:
  id-token: write  # Required for OIDC
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_OIDC_SUB_ID }}
  GROUP: ${{ github.event.inputs.resource_group }}
  LOCATION: ${{ github.event.inputs.location }}
  CREATE_SIG_VERSION: ${{ github.event.inputs.create_sig_version }}

jobs:
  build:
    name: Build partitioned VM Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_OIDC_SUB_ID }}

      - name: Build triple partitioned image
        run: |
          ./scripts/setup/craft_triple_partition_boot_disk.sh
